version: 2.1

jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: apt-get install -y make libssl-dev
      - run: make examples OPENSSL_VERSION=openssl_1.1.x
  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: apt-get install -y make libssl-dev
      - run: make examples OPENSSL_VERSION=openssl_1.1.x

workflows:
  version: 2.1

  commit:
    jobs:
      - vs-ponyc-release

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master
